fix(config): alleviate panic on blank config filee
Whenever the config parse was parsed an empty config,
a panic would result because of trying to process an
empty vector:

---- config::tests::test_blank_config stdout ----
thread 'config::tests::test_blank_config' panicked at 'index out of bounds: the len is 0 but the index is 0', src/config.rs:237:33

This commit alleviates that by simply returning an empty
Hotkey vector whenever an empty config is passed.